### GET comments of a post
GET http://127.0.0.1:8000/api/posts/cccccccc-cccc-cccc-cccc-cccccccccccc/comments
Accept: application/json

### ADD comment
POST http://127.0.0.1:8000/api/posts/cccccccc-cccc-cccc-cccc-cccccccccccc/comments
Content-Type: application/json
Accept: application/json

{
  "from_id": "22222222-2222-2222-2222-222222222222",
  "text": "Test comment envoyé par Bob"
}

### DELETE comment
DELETE http://127.0.0.1:8000/api/posts/cccccccc-cccc-cccc-cccc-cccccccccccc/comments/c018
Content-Type: application/json
Accept: application/json
